{{- if .Values.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "AppCtx.apiName" . }}-deployment
  labels: {{ include "AppCtx.apiLabels" . | nindent 4 }}
spec:
  replicas: 3
  selector:
    matchLabels: {{ include "AppCtx.apiSelectorLabels" . | nindent 8 }}
  template:
    metadata:
      labels: {{ include "AppCtx.apiLabels" . | nindent 10 }}
    spec:
      imagePullSecrets:
        - name: auth-master3-registry
      containers:
      - name: api
        image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "100Mi"
            cpu: "0.1"
          limits:
            memory: "300Mi"
            cpu: "0.5"
        env:
          - name: DB_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: {{ template "AppCtx.apiName" . }}-cm
                key: DB_ENDPOINT
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: {{ template "AppCtx.apiName" . }}-cm
                key: DB_NAME
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ template "AppCtx.dbName" . }}-credentials  # Nom du secret
                key: pg_username     # nom de la clef dans le config map
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "AppCtx.dbName" . }}-credentials  # Nom du secret
                key: pg_password
{{- end }}
