{{- if .Values.api.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "AppCtx.apiName" . }}-cm
  labels: {{ include "AppCtx.apiLabels" . | nindent 4 }}
data:
  DB_ENDPOINT: '{{ template "AppCtx.dbName" . }}-service:{{ .Values.db.servicePort }}'
  DB_NAME: {{ .Values.db.name }}
{{- end }}
