{{- if .Values.api.enabled }}
{{- if .Values.api.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels: {{ include "AppCtx.apiLabels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if .Values.api.ingress.tls.enabled }}
    cert-manager.io/cluster-issuer: letsencrypt-staging
    {{- end }}
  name: {{ template "AppCtx.apiName" . }}-ingress
spec:
  rules:
  - host: {{ .Values.api.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ template "AppCtx.apiName" . }}-service
            port:
              number: {{ .Values.api.servicePort }}
        path: /
        pathType: Prefix
{{- if .Values.api.ingress.tls.enabled }}
  tls:
  - hosts:
      - {{ .Values.api.ingress.host }}
    secretName: {{ template "AppCtx.apiName" . }}-ingress-tls
    {{- end }}  
  {{- end }}  
{{- end }}
