{{- if .Values.front.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "AppCtx.frontName" . }}-service
  labels: {{ include "AppCtx.frontLabels" . | nindent 4 }}
spec:
  selector: {{ include "AppCtx.frontSelectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.front.servicePort }}
      targetPort: 80
{{- end }}
