{{- if .Values.db.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "AppCtx.dbName" . }}-credentials
  labels: {{ include "AppCtx.labels" . | nindent 4 }}
type: Opaque
data:
  pg_username: {{ .Values.db.credentials.user | b64enc }}
  pg_password: {{ .Values.db.credentials.pwd | b64enc }}
{{- end }}
